### ISSUE TITLE
Add SPS-TBTReader

### ISSUE THREAD

**Issue by JoschD** [pylhc/omc3#128]
Should be similar to: https://github.com/pylhc/Beta-Beat.src/blob/df93c2691193f1258e78d240508a3354517bff11/MODEL/SPS/Tools/convert_0.2.py

We don't have an example file, so maybe look in /nfs/cs-ccr-nfs4/sps_data/OP_DATA/multit/betabeat/2012-11-08/SPS/Measurements

As no one has used this since 2017, this issue has HIGH PRIORITY!!!

**Comment by Mael-Le-Garrec** [comment]
As I understand the file to be read is a SDDS file, but what's the output?

**Comment by JoschD** [comment]
> As I understand the file to be read is a SDDS file, but what's the output?

See `reader_` files in `tbt` folder.

**Comment by mihofer** [comment]
Some first data/sdds from the new multiturn GUI is now available for SPS. It is formatted as ASCII sdds with some variables different than in the LHC ASCII sdds (time split in date, timen milliseconds fields, etc.). Current implementation is still subject to change (likely minor ones though) but might be a good time to start.
[MULTITURN_ACQ__16-09-20_13-41-31.zip](https://github.com/pylhc/omc3/files/5383269/MULTITURN_ACQ__16-09-20_13-41-31.zip)

**Comment by JoschD** [comment]
Fixed downstream in the tbt-reader ( https://github.com/pylhc/turn_by_turn/blob/master/turn_by_turn/sps.py ) , which can be selected via the appropriate flag in omc3
