### ISSUE TITLE
do (some) todos

### ISSUE THREAD

**Issue by mihofer** [pylhc/omc3#174]
accelerator kwargs in hole in one: write kwargs from accel class and/or point to accel class file and class files inheriting from this one, chromatic beating option etc. missing in docstring
updated readme: fix typo (clone which, perform frequency _analysis_ ), add packages tfs, sdds, generic-parser and links to repos
general: fix Future warnings

**Comment by fsoubelet** [comment]
https://github.com/pylhc/omc3/blob/c3acd867dc105dbcb3a58ff15a29d5e44353b561/omc3/model/write_macros.py#L15

replace `:` with `;`

**Comment by mihofer** [comment]
I think except for the future warnings all issues in here have been closed, so closure might be in order .. or keep it as a small issue bucket? Opinions @fsoubelet @JoschD @lmalina @awegsche

**Comment by fsoubelet** [comment]
I'd say we close this issue once the branch in which fixes are implemented gets merged. I don't think keeping up an issue with a vague name is going to help in the long term compared to a few specific ones.

**Comment by mihofer** [comment]
fixes were implemented in different branches, most of them afaik already merged to master, Issue is now linked with PR #191 as that's the last problem to be fixed
