### ISSUE TITLE
create agreed-on mplstyles for omc and omc_presentation

### ISSUE THREAD

**Issue by JoschD** [pylhc/omc3#204]
There are the `standard.mplstyle` and `presentation.mplstyle` in the `omc3.plotting.styles` folder. 
These are my personal preference and not everyone might be happy about them. 

How should we discuss them?

**Comment by JoschD** [comment]
hint: you can create your own `.mplstyle` file and give its path as input to the `plot_tfs` and `plot_optics_measurements`. I can be even only a short file with updates to other styles, input then like:
`style = ['standard', 'path/to/my_delta.mplstyle']`

**Comment by fsoubelet** [comment]
Nice initiative. Maybe we should all take some time to use these styles a bit and see how we feel about them, then have a chat / meeting?
