### ISSUE TITLE
Setting NumPy seeds in tests

### ISSUE THREAD

**Issue by lmalina** [pylhc/omc3#212]
When we set globally the NumPy seeds. The actual seed used is order dependent (the order in which the tests are collected and run), as the setting happens at the time of test collection. This is just to be aware of this in future, it is not a problem now.

**Comment by mihofer** [comment]
Both test_harpy and test_measure_optics now define the seeds during the setup of each test function and not globally anymore.
As such, any future tests should follow this example and this issue could be closed then.
