### ISSUE TITLE
add Lumi Imbalance script

### ISSUE THREAD

**Issue by mihofer** [pylhc/omc3#223]
add script /afs/cern.ch/eng/sl/lintrack/LHC_commissioning2017/LumiImbalance.py to calc lumi imbalance from kmod results into omc3

**Comment by Mael-Le-Garrec** [comment]
Where would you put it in omc3? I wanna do it :)

**Comment by mihofer** [comment]
omc3/omc3/scripts .. my idea of an implementation was to read a twiss file where the kmod results are compiled (i.e rows IP1B1, IP1B2, IP5B1, IP5B2) and then perform the calculation of the imbalance and print to cmd/ add to header of the input file .. 
(and dont forget to add to README)

**Comment by lmalina** [comment]
This should be probably combined with a script to load the kmod results per IP and per beam
