### ISSUE TITLE
Fix --nonlinear option of hole_in_one

### ISSUE THREAD

**Issue by lmalina** [pylhc/omc3#236]
Currently, it has two choices "rdt" and "crdt" and zero to two of them can be selected. However if no nonlinear calculation is selected, one cannot rerun the analysis with config file it has produced. This could (and maybe should) be fixed directly in generic parser.

**Comment by mihofer** [comment]
related to this issue i guess https://github.com/pylhc/generic_parser/issues/26

**Comment by JoschD** [comment]
Quick fix would be probably using the [utils.iotools.save_config](https://github.com/pylhc/omc3/blob/19e4305b764b38ca215c8a3f3f57e2ba8c7003cd/omc3/utils/iotools.py#L276) function

**Comment by lmalina** [comment]
> related to this issue i guess [pylhc/generic_parser#26](https://github.com/pylhc/generic_parser/issues/26)

Yes and no, [pylhc/generic_parser#26] treats `None`'s, here I think changing `nargs=+` to`nargs=*` could solve the problem, since the default is set to empty list.
