### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by fsoubelet** [pylhc/omc3#263]
Opening an issue as I'm tweaking the documentation a bit.

Changes include:
- a new css theme
- a bit of info on the landing page
- including the omc logo (thanks @JoschD for the `.svg`)
- tweaks in the ToC

**Comment by fsoubelet** [comment]
Looks like this for now:

<img width="1680" alt="Screenshot 2020-11-10 at 12 26 19" src="https://user-images.githubusercontent.com/19598248/98676438-84129480-2353-11eb-8048-9924a44e78db.png">

**Comment by Mael-Le-Garrec** [comment]
> Looks like this for now:

THIS LOOKS GOOD!

**Comment by fsoubelet** [comment]
Segment including some code:

<img width="1680" alt="Screenshot 2020-11-10 at 13 56 23" src="https://user-images.githubusercontent.com/19598248/98676938-32b6d500-2354-11eb-9418-78b6052e65da.png">
