### ISSUE TITLE
Rolling problem when calculating std for low values

### ISSUE THREAD

**Issue by JoschD** [pylhc/omc3#271]
Pandas rolling `std()` function will not work for small numbers (i.e. `<1e-8`), which we might encounter in the error values, from pandas version `1.2.0`, see https://github.com/pandas-dev/pandas/issues/37051 and https://github.com/pandas-dev/pandas/issues/39872 .

As we are using this for cleaning purposes in [`bbq_tools`](https://github.com/pylhc/omc3/blob/764da09caf57e166665bf5d6fe48f38107557581/omc3/tune_analysis/bbq_tools.py#L90) we should replace this by a manual rolling loop.

**Comment by JoschD** [comment]
Should be fixed in newer pandas versions: https://github.com/pandas-dev/pandas/pull/40505

To be tested!

**Comment by fsoubelet** [comment]
I guess that will simply make us force `!= 1.2` in the dependencies then?

**Comment by JoschD** [comment]
Just tested in `pandas 1.3.1` and it works correctly again. So yes, `!= 1.2` will work!

**Comment by JoschD** [comment]
We have `!= 1.2` in the dependencies for this reason. Fixed.
