### ISSUE TITLE
Add windows and macOS test for python 3.9

### ISSUE THREAD

**Issue by JoschD** [pylhc/omc3#282]
Windows and MacOS tests for python 3.9 have been removed, 
as no official wheels are present for pyTables  (https://pypi.org/project/tables/#files) and building oneself is prone to errors.
Solutions:

- waiting for wheels to become available (https://github.com/PyTables/PyTables/issues/823)
- build ourselves
- use the inofficial packages, but it's not quite clear how to use these within the installation workflow (http://www.pytables.org/usersguide/installation.html)

**Comment by mihofer** [comment]
Temp. fix could also be applied for cron jobs

**Comment by mihofer** [comment]
Tests in cron jobs were removed in #319

**Comment by JoschD** [comment]
All wheels are available until python 3.11. And the tests are back for a while now.
