### ISSUE TITLE
Review the default values in the GUI/Python

### ISSUE THREAD

**Issue by tpersson** [pylhc/omc3#300]

**Comment by JoschD** [comment]
Hint for the GUI: These can be easily implemented into the accelerators. Check there (or with me) first how it is done, as we put already a comfortable way in place.

**Comment by JoschD** [comment]
Related: https://its.cern.ch/jira/projects/BBGUI/issues/BBGUI-173

**Comment by JoschD** [comment]
This is done continuously one default value at a time, it seems.
