### ISSUE TITLE
Coupling Output: Unified Column Names

### ISSUE THREAD

**Issue by JoschD** [pylhc/omc3#305]
As discussed, the coupling output files should follow the column naming conventions as the RDTs, i.e. 
```
*                 NAME                    S                COUNT                  AMP               ERRAMP                PHASE             ERRPHASE                 REAL                 IMAG
```
(+ DELTA and MDL columns, e.g. see beta_amplitude_[xy].tfs)
instead it is 

```
* NAME                                    S               F1001R               F1001I               F1001W            F1001IMDL          DELTAF1001I       ERRDELTAF1001I            F1001RMDL          DELTAF1001R       ERRDELTAF1001R            F1001WMDL          DELTAF1001W       ERRDELTAF1001W
```

**Comment by awegsche** [comment]
do we need the `COUNT` column? `COUNT` will be just the number of input files. It will always be the same for all the BPMs.

There is no mechanism in the algorithm that could yield any other result.
