### ISSUE TITLE
review names of constants

### ISSUE THREAD

**Issue by awegsche** [pylhc/omc3#336]
The following constants need pre- (or suf-)fixes stating their intention (e.g. `COL` or `COLUMN` for column names, `SUF` or `SUFFIX` for a suffix etc):

https://github.com/pylhc/omc3/blob/6763e865ce40ea0c34d02d1c5039574004c677ef/omc3/optics_measurements/constants.py#L21-L51

**Comment by fsoubelet** [comment]
I am currently consolidating constants.

**Comment by mihofer** [comment]
maybe we could combine this issue with #231 and #305 (and similar issues that I may have overlooked) to something á la `restructure column naming`, also in view of having one constants dir for all the const (correction, kmod, optics_meas)
the problem, for now, is still that the order of where to put these -fixes is still up to the implementer for the specific module.
Maybe some simple functions could be written to also define the order in the constants module, e.g. an `err_column(var)` fct which returns `f"{ERR}{var}"` .. or alternative, and a lot more type work, spell out every column as constant here

**Comment by awegsche** [comment]
> maybe we could combine this issue with #231 and #305 (and similar issues that I may have overlooked) to something á la `restructure column naming`, also in view of having one constants dir for all the const (correction, kmod, optics_meas) the problem, for now, is still that the order of where to put these -fixes is still up to the implementer for the specific module. Maybe some simple functions could be written to also define the order in the constants module, e.g. an `err_column(var)` fct which returns `f"{ERR}{var}"` .. or alternative, and a lot more type work, spell out every column as constant here

We shouldn't start bundling together issues and pull requests. I deliberately opened this as separate issue to avoid discussions on this one blocking other, more important issure like #305.

**Comment by fsoubelet** [comment]
I agree that we should go for atomic PRs. I am also not a fan of having functions in the constants modules.

**Comment by JoschD** [comment]
Closing, as I also think this is part of #231
