### ISSUE TITLE
[Bug]: Pypi install does not include kmod sequences

### ISSUE THREAD

**Issue by mihofer** [pylhc/omc3#355]
### Documentation

- [X] Yes

### Operating System

CentOS 7.9

### Python Version

3.7

### Package Version

2.1

### Bug Description

When running the `run_kmod` script after installing it via `pip install omc3`, an error occurs as the files in the `sequence` directory in the `kmod` folder are missing.

### Possible Fix Implementation

Add `graft omc3/kmod/sequences ` to the `MANIFEST.in`.

**Comment by fsoubelet** [comment]
I can confirm that the `sequences` folder is not part of the distribution one can get from `PyPI`. Should indeed be added to the `MANIFEST` file.
