### ISSUE TITLE
[Feature Request]: Beta from phase: Catch too few BPMs in 3BPM method early

### ISSUE THREAD

**Issue by JoschD** [pylhc/omc3#361]
### Feature Description

If there are too few BPMs left after cleaning (e.g. 2), beta-from-phase will crash with a nondescript index error in the 3 BPM method. Probably also N-BPM method (?). This should be caught early and the user informed properly.

### Possible Implementation

check for number of BPMs left in input to beta-from-phase and raise error

**Comment by JoschD** [comment]
any progress on that one, btw?

**Comment by awegsche** [comment]
I can add a warning "Dear user, phase analysis yields less than 3 BPMs. This will probably lead to problems later on, especially in beta from phase. Please check your measurement"

**Comment by awegsche** [comment]
yeah, that's what I wanted to do
