### ISSUE TITLE
[Bug]: b2_systematic_errors are missing for 6.8TeV

### ISSUE THREAD

**Issue by fsoubelet** [pylhc/omc3#372]
### Documentation

- [X] Yes

### Python Version

3.9.7

### Package Version

0.2.6

### Bug Description

When doing model creation for 6.8TeV and including the b2_errors, model creation fails.

This is because the `madx` run will look for a file in `omc3/model/accelerators/lhc/systematic_errors/b2_errors_settings/beam[12]_6800GeV.madx`

This file does not exist.

### Steps to Reproduce

Simple steps would be: load up a GUI, create a model at 6.8TeV (any optics), and require b2 errors

### Possible Fix Implementation

We include the right files: `beam[12]_6800GeV.madx`

**Comment by fsoubelet** [comment]
@mihofer @JoschD @tpersson @awegsche 

Do you have any idea where / how I could get the correct file / values for 6800GeV?

**Comment by JoschD** [comment]
@fsoubelet Is this still a thing? We have it now in the new model creation, no?

**Comment by fsoubelet** [comment]
Yes @JoschD it seems this is accessible nowadays
