### ISSUE TITLE
[Feature Request]: BBS2OMC3 converter - Add missing coupling columns

### ISSUE THREAD

**Issue by JoschD** [pylhc/omc3#409]
### Feature Description

Coupling files are not taken into account by the converter yet. To be implemented

**Comment by fsoubelet** [comment]
That's surprising, I did write [a function for it](https://github.com/pylhc/omc3/blob/95238310fca278f4a4fda1c0094859450be5e6f2/omc3/scripts/betabeatsrc_output_converter.py#L400) and it [is called in the main](https://github.com/pylhc/omc3/blob/95238310fca278f4a4fda1c0094859450be5e6f2/omc3/scripts/betabeatsrc_output_converter.py#L121).

It there a problem in the implementation? In which way did it fail?

**Comment by JoschD** [comment]
Oh, sorry. I didn't see your function, I just didn't get any output files for coupling, so I assumed it was missing. I will check and get back to you

**Comment by JoschD** [comment]
It is missing columns: NAME, ERRREAL and ERRIMAG
