### ISSUE TITLE
[Bug]: Pandas to numpy dtype conversions bug.

### ISSUE THREAD

**Issue by JoschD** [pylhc/omc3#453]
### Bug Description

Pandas to numpy dtype conversions for the lin files went wrong and numpy had 'obj' arrays, 
as it didn't seem to recognize the `pd.Float64` as `float64`.
This happened only when using multiple files as input, as the `np.average()` function seem to have been the main culprit. 

A good fix would convert the dataframes as soon as possible to `np.float64`

**Comment by fsoubelet** [comment]
Closed by #455
