### ISSUE TITLE
create a more accelerator independent data loading routine

### ISSUE THREAD

**Issue by mihofer** [pylhc/omc3#66]
idea is to allow loading also non-lhc/non-sdds data without previous conversion to sdds

- [ ]  split up tbt.handler.py in data_class.py containing the class TbtData and var. accel_handler.py which all implement the read_tbt function to read the specific files (possibly also write_tbt etc.)

- [ ] in hole_in_one.py / _run_harpy select then appropriate module to import and read tbt

**Comment by JoschD** [comment]
Fixed by #74
