### ISSUE TITLE
bug in outliers.py

### ISSUE THREAD

**Issue by awegsche** [pylhc/omc3#69]
The line 
https://github.com/pylhc/omc3/blob/398bed5d675a4ccde17ae3e0fd88752569274627/omc3/utils/outliers.py#L44

has an issue:

With `std` being a list, the `max`  function will result in
`np.max(limit, np.array([some_value]))`

If `some_value` is higher than limit, the result is `[some_value]` which is a list and cannot be compared by `<` with `np.abs(...)`.

**Proposed solution:**
change to
`mask = np.logical_and(mask,np.abs(y_orig - avg) < np.max(np.append(nsig * std, limit)))`

**Comment by awegsche** [comment]
fixed in 17c81615bf7c497967e5a2004d10e944f32c859c

**Comment by lmalina** [comment]
closed by #49
