### ISSUE TITLE
Create function to automatically save input arguments as config file

### ISSUE THREAD

**Issue by JoschD** [pylhc/omc3#71]
Usage is similar to the command.run, but way easier to read.

**Comment by JoschD** [comment]
[[https://github.com/pylhc/omc3/commit/81244cb7107d1380e58470b31a9c96820988ab14]]
Provides a function like this, which can be given `opt` and `unknown`. 
The question is, where to put it?

**Comment by lmalina** [comment]
Fixed by #72
