### ISSUE TITLE
Proposal: Create definition-classes for output files

### ISSUE THREAD

**Issue by JoschD** [pylhc/omc3#76]
In my opinion all output files should be fixed as classes in the code, which define output name and columns as well as column types. Maybe even headers.

Every reference to a column should then be handled by referring to the column of the respective class as a constant.

Also this would limit the problem with the tfs-writer that occurs sometimes, when you don't define the cloumn data-type and it tries to guess.

Should be combined somehow with tfs-collection.

**Comment by JoschD** [comment]
Created in tfs 1.0.3 . To be used.

**Comment by mihofer** [comment]
As #38 is now in action, should this be closed or is there further steps necessary?

**Comment by mihofer** [comment]
#38 is in action --> closed
