### ISSUE TITLE
Move K-mod from Beta-Beat.src

### ISSUE THREAD

**Issue by lmalina** [pylhc/omc3#8]
- [x] Make python 3 compatible
- [x] Use tfs package
- [x] Create a single top-level entry point
- [x] Refactor

**Comment by JoschD** [comment]
For analysis in kmod_utils use as 
def calc_std(val):
    return np.sqrt(sum([max(val[i-1] - val[0], val[i] - val[0])**2 for i in 2*(np.arange(len(val))+1]))

**Comment by JoschD** [comment]
gui2kmod: check BBS for filenames

``def get_beta_filename(plane):
    return "getkmodbeta{:s}.out".format(plane)``


``def get_beta_star_filename():
    return "beta_star.out"``


``def get_results_filename():
    return "results.out"``

**Comment by JoschD** [comment]
- [ ] Make pep8 compatible (long lines, double linebreaks between functions)
- [ ] Write some documentation, maybe formulas of functions into docstrings
- [ ] Write Accuracy tests

**Comment by mihofer** [comment]
Closed with #20 , some follow up issues to be fixed at a later point
