### ISSUE TITLE
Possibilty of adding hooks in hole_in_one.py

### ISSUE THREAD

**Issue by mihofer** [pylhc/omc3#92]
discuss possible ways to add hooks in the scripts to perform actions before/after loading tbt-data, cleaning, harmonic analysis, optics, ...

potential application e.g. add noise after reading in a ptc trackone file, ..

**Comment by awegsche** [comment]
I agree for the noise, this would be a reasonable addition. Often (e.g. for accuracy tests) we would need to add a noise level as is expected _after_ cleaning to simulate measurement input for measure_optics.

For the actions like cleaning and analysis I am curious about how a possible way would look like. Do you already have something in mind?

**Comment by mihofer** [comment]
Adding noise is taking care of in tbt_converter, no general implementation of hooks planned anymore due to lack of unique use cases
