### ISSUE TITLE
Exact position in logging output

### ISSUE THREAD

**Issue by awegsche** [pylhc/omc3#96]
**New Feature**:

Let the logger print the exact position where a message is issued, at least for DEBUG and DIAGNOSTIC level messages. Optionally also for WARNING and ERROR.
For INFO level messages this is not suitable because it will create a mess in the command line output. Also it exposes implementation details to the user.

**Use cases**:

- Whenever a change causes problems downstream in the execution line, it would help a lot to know where this happens exactly in order to spot the actual problem faster.
- An external tool (input handler) or a new accelerator class have to provide a lot of functionality. Implementing a new component of this size and importance might profit a lot from more precise debug output.

**Implementation Proposition**:

- add `{Separator} {filename} line {line}` to the Logger format
- or use gdb style: add `{Separator} {filename}:{line}`

optionally change the existing `{name}` to `{filename}` and save a few characters

**Comment by awegsche** [comment]
A quick look into Python's logging docs reveals that the corresponding keywords are `pathname` and `lineno`.

So, change the format to, e.g.
`'%(levelname)7s {div:s} %(message)s {div:s} %(name)s {div:s} %(pathname):%(lineno)'.format(div=DIVIDER)`

**Comment by awegsche** [comment]
example:

<pre><font color="#9696FF">  DEBUG </font><font color="#7F7F7F">| </font><b>Unknown Options: &apos;[&apos;accel&apos;, &apos;files&apos;, &apos;outputdir&apos;, &apos;model_dir&apos;, &apos;compensation&apos;]&apos;. </b><font color="#7F7F7F">| generic_parser.dict_parser | /media/awegsche/HDD/omc3/omc3/generic_parser/dict_parser.py:176</font>
<font color="#9696FF">  DEBUG </font><font color="#7F7F7F">| </font><b>Unknown Options: &apos;[&apos;accel&apos;, &apos;model_dir&apos;]&apos;. </b><font color="#7F7F7F">| generic_parser.dict_parser | /media/awegsche/HDD/omc3/omc3/generic_parser/dict_parser.py:176</font>
</pre>

**Comment by JoschD** [comment]
I don't think this will help a lot, as it will make reading the logging messages very annoying. 
The logging should not be used to find positions in the code but rather to give information about what is going wrong. 
As the module is shown anyway, it should be easy to find the location by just searching for the logging message.

**Comment by awegsche** [comment]
Well it is not a super important feature but it would make finding the problem faster and more convenient.
The alternative is to raise an error instead of just logging when something is going wrong. But this could limit productivity because it will stop the analysis.
Also we are not even talking about this situation. Sometimes debug logs can give you a hint of some problem that does not seem critical at first glance.

Searching for the logging message adds some inconvenience and nothing prevents a developer from printing the same message on several positions.

**Comment by lmalina** [comment]
I agree with Josch, in such extended logging would be harder to find anything.

**Comment by awegsche** [comment]
Firstly
> ..., in such extended logging would be harder to find anything

is not true.

But if this is such a concern to you, there is the intermediate proposal to only add the line to the logging. This would not give the full convenience of just pointy-clicky into the output to get to the actual place of interest but -- as Josch pointed out -- the module name translates to filename and one has at least all the information at hand.

**Comment by awegsche** [comment]
Apart from that, it is two votes against and one for the proposal at the moment. For the time being I will continue to do exact logging on my branches.

**Comment by lmalina** [comment]
This looks like pure code development concern, which is upon everyone. For the master branch, I wouldn't go this way. Other opinions? Otherwise closing the issue...
