### ISSUE TITLE
hole_in_one's --accel option doesn't accept accelerator class

### ISSUE THREAD

**Issue by awegsche** [pylhc/omc3#97]
**The problem**:

The option `--accel` in the hole_in_one entrypoint, defined in 
https://github.com/pylhc/omc3/blob/297cb7fd00ab3a4b2bec42176d71e66d55ecd93b/omc3/model/manager.py#L23-L24

only accepts strings although the help string suggests otherwise.

Giving an accelerator class as input, I get a crash even before the actual exception can be raised:
<pre><font color="#CD3232"><b>ERR: </b></font>  File <font color="#CDCDFF"><b>/media/awegsche/HDD/omc3/omc3/generic_parser/dict_parser.py</b></font>: line <font color="#00C800"><b>134</b></font>, in <b>_check_value</b>
<font color="#6482FF">FILE </font>    <font color="#64C864">129 </font>                raise ArgumentError(f&quot;All elements of &apos;{key:s}&apos; need to be one of &quot;
<font color="#6482FF">FILE </font>    <font color="#64C864">130 </font>                                    f&quot;&apos;{param.choices:}&apos;, instead the list was {opt:s}.\n&quot;
<font color="#6482FF">FILE </font>    <font color="#64C864">131 </font>                                    f&quot;Help: {param.help:s}&quot;)
<font color="#6482FF">FILE </font>    <font color="#64C864">132 </font>
<font color="#6482FF">FILE </font>    <font color="#64C864">133 </font>        elif param.choices and opt not in param.choices:
<font color="#6482FF">FILE </font>--&gt; <font color="#00C800"><b>134 </b></font>            raise ArgumentError(f&quot;&apos;{key:s}&apos; needs to be one of &apos;{param.choices:}&apos;, &quot;
<font color="#6482FF">FILE </font>    <font color="#64C864">135 </font>                                f&quot;instead it was {opt:s}.\n&quot;
<font color="#6482FF">FILE </font>    <font color="#64C864">136 </font>                                f&quot;Help: {param.help:s}&quot;)
<font color="#6482FF">FILE </font>    <font color="#64C864">137 </font>        return opt
<font color="#6482FF">FILE </font>    <font color="#64C864">138 </font>
<font color="#6482FF">FILE </font>    <font color="#64C864">139 </font>    def _parse_arguments(self, arg_dict, param_dict):
</pre>
<pre><font color="#CD3232"><b>ERR: </b></font><font color="#32F0FF">TypeError</font>: unsupported format string passed to type.__format__
</pre>

because a class cannot be formatted as string, which is required in `{opt:s}` above.

**Possible solutions**:

- Fix the help string and state that actually only strings are allowed.
- Make manager also take accelerator classes as input ( _I vote for this one_ )

**Comment by lmalina** [comment]
This is the code used to get accelerator class or instance in a generic way. The first option should be used (fix the help string). If you already have an accelerator class, just pass <your_class>.NAME
