### ISSUE TITLE
Allow hole_in_one to take a fully generated accelerator instance

### ISSUE THREAD

**Issue by awegsche** [pylhc/omc3#98]
**Extension of functionality** 

Related to #97, an extension to the documented but broken behaviour of hole_in_one's `--accel` option might be useful:

Take one of the following:

- [existing] name of the accelerator (lhc, petra, ...) and construct it either from args (nattunes, excitation) or from model dir 
- [not working] accelerator class which is then filled by argument or model dir
- [not there] accelerator instance, already filled with twisses etc.

**Comment by lmalina** [comment]
Similar to #97 , the option should be a string, hole_in_one is a top-level script, which passes the option to obtain accelerator class. Alternatively <class>.NAME can be passed. In fact, this refers to the very same option as in #97 ... closing.
